version: '3.8'

networks:
  default:
    driver: bridge

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ecommerce-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - default

  node-server-nestjs:
    container_name: node-server-nestjs
    image: node-server-nestjs
    command: npm run start:prod
    environment:
      DATABASE_URL: "postgresql://root:123456@postgres:5432/ecommerce-db?schema=public"
    ports:
      - "3000:3000"
    volumes:
      - .:/user/src/app
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - default

volumes:
  postgres_data: